(function(){
  'use strict';
  const Slot=window.Slot,KEY='bankCollectPlayerV23',LEGACY_KEY='bankCollectPlayerV18';const Economy=Slot.Economy={data:null,cashoutPromise:null};
  const fresh=()=>({credits:Number(Slot.Config.game.startingCredits)||10000,debt:0,everHadDebt:false,debtStartedAt:0,playerName:'PLAYER',pigGrowthScale:1,pendingSubmissionId:''});
  Economy.load=function(){let data;try{data=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(LEGACY_KEY)||'null');}catch(_){data=null;}Economy.data=Object.assign(fresh(),data||{});const days=Math.max(1,Number(Slot.Config.economy?.debtResetDays)||30),age=Date.now()-(Number(Economy.data.debtStartedAt)||0);if(Economy.data.debt>0&&age>=days*86400000){Economy.data.debt=0;Economy.data.debtStartedAt=0;}Slot.State.credits=Math.max(0,Number(Economy.data.credits)||0);Slot.Config.pig.currentGrowthScale=Slot.Utils.clamp(Number(Economy.data.pigGrowthScale)||1,1,Number(Slot.Config.pig.maxScale)||4);Slot.Rendering.applyLayout();Economy.save();return Economy.data;};
  Economy.save=function(){if(!Economy.data)return;Economy.data.credits=Math.max(0,Number(Slot.State.credits)||0);Economy.data.pigGrowthScale=Slot.Utils.clamp(Number(Slot.Config.pig.currentGrowthScale)||1,1,Number(Slot.Config.pig.maxScale)||4);try{localStorage.setItem(KEY,JSON.stringify(Economy.data));}catch(_){}};
  Economy.borrow=function(amount){amount=Math.round(Number(amount)||0);const c=Slot.Config.economy||{},min=Number(c.borrowMin)||1000,max=Number(c.borrowMax)||10000,step=Number(c.borrowStep)||1000;if(amount<min||amount>max||amount%step)return{ok:false,message:'Choose a valid rebuy amount.'};if(Slot.State.credits>=Math.min(...Slot.Config.game.betLevels))return{ok:false,message:'Rebuy is available below the minimum bet.'};Economy.data.debt+=amount;Economy.data.everHadDebt=true;if(!Economy.data.debtStartedAt)Economy.data.debtStartedAt=Date.now();Slot.State.credits+=amount;Economy.save();return{ok:true,message:`${amount.toLocaleString()} credits added.`};};
  Economy.repay=function(){const paid=Math.min(Economy.data.debt,Slot.State.credits);if(paid<=0)return{ok:false,message:'No credits are available to repay debt.'};Economy.data.debt-=paid;Slot.State.credits-=paid;if(Economy.data.debt<=0){Economy.data.debt=0;Economy.data.debtStartedAt=0;}Economy.save();return{ok:true,message:`Repaid ${paid.toLocaleString()} credits.`};};
  Economy.cashoutEligibility=function(){const debt=Number(Economy.data.debt)||0,min=Economy.data.everHadDebt?Number(Slot.Config.economy.cashoutMinimumWithDebt):Number(Slot.Config.economy.cashoutMinimumNoDebt);if(debt>0)return{ok:false,message:`Repay ${debt.toLocaleString()} debt first.`};if(Slot.State.credits<min)return{ok:false,message:`At least ${min.toLocaleString()} credits required.`};return{ok:true,min};};
  Economy.request=async function(action,payload={}){const url=String(Slot.Config.economy?.leaderboardEndpoint||'').trim();if(!url)throw new Error('Set the Google Sheets leaderboard URL in the editor.');const response=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});if(!response.ok)throw new Error(`Leaderboard returned ${response.status}`);const result=await response.json();if(result?.ok===false)throw new Error(result.error||'Leaderboard request failed.');return result;};
  Economy.getLeaderboard=()=>Economy.request('list',{limit:Number(Slot.Config.economy.leaderboardLimit)||25});
  Economy.cashout=function(name){if(Economy.cashoutPromise)return Economy.cashoutPromise;Economy.cashoutPromise=(async()=>{const eligible=Economy.cashoutEligibility();if(!eligible.ok)throw new Error(eligible.message);name=String(name||'PLAYER').trim().slice(0,24)||'PLAYER';Economy.data.playerName=name;const score=Math.round(Slot.State.credits),submissionId=Economy.data.pendingSubmissionId||`${Date.now()}-${Math.random().toString(36).slice(2)}-${score}`;Economy.data.pendingSubmissionId=submissionId;Economy.save();await Economy.request('submit',{name,score,submissionId});Slot.State.credits=Number(Slot.Config.game.startingCredits)||10000;Economy.data.debt=0;Economy.data.debtStartedAt=0;Economy.data.pendingSubmissionId='';Economy.save();Slot.UI.updateHud();Slot.UI.refreshAccount?.(`${score.toLocaleString()} submitted. Account reset.`);return score;})().finally(()=>Economy.cashoutPromise=null);return Economy.cashoutPromise;};
  window.addEventListener('beforeunload',()=>Economy.save());document.addEventListener('visibilitychange',()=>{if(document.hidden)Economy.save();});
  const boot=()=>setTimeout(()=>{Economy.load();const original=Slot.UI.updateHud;Slot.UI.updateHud=function(){original();Economy.save();};const growPig=Slot.Animation.growPig,restorePig=Slot.Animation.restorePig;Slot.Animation.growPig=async function(...args){const result=await growPig.apply(this,args);Economy.save();return result;};Slot.Animation.restorePig=function(...args){const result=restorePig.apply(this,args);Economy.save();return result;};Slot.UI.updateHud();Slot.UI.bindEconomy();Slot.UI.bindAutoSpin();},0);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
