(function () {
  'use strict';
  const Slot=window.Slot;const UI=Slot.UI={popupTimer:null,popupResolve:null};
  UI.updateHud=function(){document.getElementById('credits-value').textContent=Math.round(Slot.State.credits).toLocaleString();document.getElementById('bet-value').textContent=Math.round(Slot.State.bet).toLocaleString();document.getElementById('win-value').textContent=Math.round(Slot.State.lastWin||0).toLocaleString();};
  UI.setMessage=text=>document.getElementById('message-text').textContent=text;
  UI.setButtonsLocked=function(locked){['bet-minus','bet-plus','cashout-button','leaderboard','pays-button'].forEach(id=>{const el=document.getElementById(id);if(el)el.disabled=!!locked;});};
  function pressCfg(key){return Object.assign({},Slot.Config.buttonPress||{},Slot.Config.buttonPressByButton?.[key]||{});}function pressDuration(key){return Math.max(30,Number(pressCfg(key).durationMs)||105);}
  UI.pressStandalone=function(el,key){if(!el||el.disabled)return;el.classList.remove('is-pressed');void el.offsetWidth;el.classList.add('is-pressed');setTimeout(()=>el.classList.remove('is-pressed'),pressDuration(key));};
  UI.pressPanel=function(key,hotspot){if(!hotspot||hotspot.disabled)return;const layer=document.querySelector(`.panel-pressed-layer[data-segment="${key}"]`);layer?.classList.remove('active');hotspot.classList.remove('is-pressed');void hotspot.offsetWidth;layer?.classList.add('active');hotspot.classList.add('is-pressed');setTimeout(()=>{layer?.classList.remove('active');hotspot.classList.remove('is-pressed');},pressDuration(key));};

  UI.dismissPopup=function(){clearTimeout(UI.popupTimer);const layer=document.getElementById('popup-layer'),card=document.getElementById('popup-card');if(layer?.classList.contains('show')){card.getAnimations().forEach(a=>a.cancel());card.animate([{opacity:1},{opacity:0}],{duration:120,easing:'ease-out',fill:'both'});layer.classList.remove('show');}const done=UI.popupResolve;UI.popupResolve=null;if(done)done();};
  UI.showPopup=function(title,value='',subtitle='',durationOverride=null){if(!Slot.Config.popup.enabled)return Promise.resolve();UI.dismissPopup();const layer=document.getElementById('popup-layer'),card=document.getElementById('popup-card'),titleEl=document.getElementById('popup-title'),valueEl=document.getElementById('popup-value'),subtitleEl=document.getElementById('popup-subtitle');titleEl.textContent=title||'';valueEl.textContent=value||'';subtitleEl.textContent=subtitle||'';titleEl.style.display=title?'':'none';valueEl.style.display=value?'':'none';subtitleEl.style.display=subtitle?'':'none';Slot.Rendering.applyPopupStyle();layer.classList.add('show');const scale=Number(Slot.Config.popup.scale)||1,kind=Slot.Config.popup.animation||'pop',from=kind==='slide'?`translate3d(0,50px,0) scale(${scale})`:`translate3d(0,0,0) scale(${kind==='pop'?scale*.55:scale})`;card.getAnimations().forEach(a=>a.cancel());card.animate([{transform:from,opacity:0},{transform:`translate3d(0,0,0) scale(${scale})`,opacity:1}],{duration:240,easing:'cubic-bezier(.2,1,.3,1)',fill:'both'});return new Promise(resolve=>{UI.popupResolve=resolve;UI.popupTimer=setTimeout(UI.dismissPopup,Math.max(100,Number(durationOverride??Slot.Config.popup.durationMs)));});};
  UI.showWinPopup=(amount,durationOverride=null)=>UI.showPopup('',Math.round(Number(amount)||0).toLocaleString(),'',durationOverride);
  UI.showBigWin=function(amount){const c=Slot.Config.bigWin||{},layer=document.getElementById('big-win-layer'),card=document.getElementById('big-win-card'),img=document.getElementById('big-win-image'),value=document.getElementById('big-win-value'),duration=Math.max(1000,Number(c.durationMs)||6000),minimumSkip=Math.min(duration,Math.max(0,Number(c.minimumSkipMs)||2000));img.src=Slot.Utils.cacheUrl(c.image);card.style.transform=`scale(${Number(c.scale)||1})`;value.style.fontSize=`${Number(c.valueFontSizePx)||76}px`;value.textContent='0';layer.classList.add('show');return new Promise(resolve=>{const start=performance.now();let finished=false,skipReady=false;const finish=()=>{if(finished)return;finished=true;value.textContent=Math.round(Number(amount)||0).toLocaleString();layer.classList.remove('show');layer.removeEventListener('pointerdown',skip);resolve();},skip=()=>{if(skipReady)finish();},tick=now=>{if(finished)return;const progress=Math.min(1,(now-start)/duration);value.textContent=Math.round((Number(amount)||0)*progress).toLocaleString();if(progress<1)requestAnimationFrame(tick);};layer.addEventListener('pointerdown',skip);setTimeout(()=>skipReady=true,minimumSkip);requestAnimationFrame(tick);});};
  UI.waitForFeatureClick=function(){const layer=document.getElementById('free-spins-feature-layer');layer.classList.add('show');return new Promise(resolve=>{const start=()=>{layer.classList.remove('show');layer.removeEventListener('pointerdown',start);resolve();};setTimeout(()=>layer.addEventListener('pointerdown',start,{once:true}),80);});};
  UI.showFreeSpinsStart=function(){const layer=document.getElementById('free-spins-feature-layer'),img=document.getElementById('free-spins-feature-symbol');layer.dataset.variant='freeSpins';img.style.display='';img.src=Slot.Utils.cacheUrl(Slot.Config.symbols.freeSpins.image);document.getElementById('free-spins-feature-title').textContent=`${Number(Slot.Config.outcomes.freeSpinsAward)||6} FREE SPINS`;document.getElementById('free-spins-feature-subtitle').textContent='CLICK ANYWHERE TO START';Slot.Rendering.applyFreeSpinFeatureStyle();return UI.waitForFeatureClick();};
  UI.showPigBurstStart=function(){const layer=document.getElementById('free-spins-feature-layer'),img=document.getElementById('free-spins-feature-symbol'),p=Slot.Config.pigBurstPopup||{};layer.dataset.variant='pigBurst';img.style.display='';img.src=Slot.Utils.cacheUrl(Slot.Config.pig.image);document.getElementById('free-spins-feature-title').textContent=p.titleText||'';document.getElementById('free-spins-feature-subtitle').textContent=p.subtitleText||'';Slot.Rendering.applyFreeSpinFeatureStyle();return UI.waitForFeatureClick();};
  UI.showBonusTotal=function(amount){const layer=document.getElementById('free-spins-feature-layer'),img=document.getElementById('free-spins-feature-symbol');layer.dataset.variant='bonusTotal';img.style.display='none';document.getElementById('free-spins-feature-title').textContent='TOTAL BONUS WIN';document.getElementById('free-spins-feature-subtitle').textContent=Math.round(Number(amount)||0).toLocaleString();Slot.Rendering.applyFreeSpinFeatureStyle();return UI.waitForFeatureClick();};
  UI.showPaytable=function(){Slot.Rendering.buildPaytable();Slot.Rendering.applyPaytableStyle();document.querySelectorAll('[data-instruction-symbol]').forEach(img=>img.src=Slot.Utils.cacheUrl(Slot.Config.symbols[img.dataset.instructionSymbol].image));document.getElementById('paytable-layer').classList.add('show');};UI.hidePaytable=()=>document.getElementById('paytable-layer').classList.remove('show');
  UI.refreshAccount=function(message=''){const d=Slot.Economy.data,c=Slot.Config.economy;document.getElementById('account-credits').textContent=Math.round(Slot.State.credits).toLocaleString();document.getElementById('account-debt').textContent=Math.round(d.debt).toLocaleString();document.getElementById('account-reset').textContent=d.debtStartedAt?new Date(d.debtStartedAt+Number(c.debtResetDays)*86400000).toLocaleDateString():'NONE';const eligible=Slot.Economy.cashoutEligibility();document.getElementById('account-status').textContent=message||(eligible.ok?'Eligible to cash out.':eligible.message);document.getElementById('cashout-name').value=d.playerName||'PLAYER';};
  UI.showAccount=function(message=''){UI.refreshAccount(message);Slot.Rendering.applyCashoutMenuStyle();document.getElementById('account-layer').classList.add('show');};
  UI.showLeaderboard=async function(){const layer=document.getElementById('leaderboard-layer'),status=document.getElementById('leaderboard-status'),list=document.getElementById('leaderboard-list');layer.classList.add('show');status.textContent='LOADING…';list.innerHTML='';try{const result=await Slot.Economy.getLeaderboard(),rows=Array.isArray(result)?result:(result.rows||[]);status.textContent=rows.length?'':'NO SCORES YET';rows.forEach((row,i)=>{const li=document.createElement('li'),name=document.createElement('span'),score=document.createElement('b');name.textContent=`${i+1}. ${String(row.name||'PLAYER')}`;score.textContent=Math.round(Number(row.score)||0).toLocaleString();li.append(name,score);list.appendChild(li);});}catch(err){status.textContent=err.message;}};
  UI.bindEconomy=function(){const replace=(id,key,action)=>{const old=document.getElementById(id),el=old.cloneNode(true);old.replaceWith(el);el.addEventListener('pointerdown',()=>key==='leaderboard'?UI.pressPanel(key,el):UI.pressStandalone(el,key));el.addEventListener('click',action);};replace('leaderboard','leaderboard',UI.showLeaderboard);replace('cashout-button','cashout',UI.showAccount);document.querySelectorAll('.menu-close').forEach(b=>b.onclick=()=>b.closest('.menu-layer').classList.remove('show'));const select=document.getElementById('rebuy-amount'),c=Slot.Config.economy;select.innerHTML='';for(let n=Number(c.borrowMin);n<=Number(c.borrowMax);n+=Number(c.borrowStep)){const o=document.createElement('option');o.value=n;o.textContent=n.toLocaleString();select.appendChild(o);}document.getElementById('rebuy-submit').onclick=()=>{const r=Slot.Economy.borrow(select.value);Slot.UI.updateHud();UI.refreshAccount(r.message);};document.getElementById('repay-submit').onclick=()=>{const r=Slot.Economy.repay();Slot.UI.updateHud();UI.refreshAccount(r.message);};document.getElementById('cashout-submit').onclick=async()=>{const status=document.getElementById('account-status');status.textContent='SUBMITTING…';try{const score=await Slot.Economy.cashout(document.getElementById('cashout-name').value);status.textContent=`${score.toLocaleString()} submitted.`;}catch(err){status.textContent=err.message;}};const music=document.getElementById('music-toggle'),sfx=document.getElementById('sfx-toggle'),labels=()=>{music.textContent=`MUSIC: ${Slot.Audio.musicMuted?'OFF':'ON'}`;sfx.textContent=`SFX: ${Slot.Audio.sfxMuted?'OFF':'ON'}`;};music.onclick=()=>{Slot.Audio.toggleMusic();labels();};sfx.onclick=()=>{Slot.Audio.toggleSfx();labels();};labels();};
  UI.bindAutoSpin=function(){const old=document.getElementById('spin-button'),spin=old.cloneNode(true);old.replaceWith(spin);let timer=null,longPress=false;const sync=()=>spin.classList.toggle('auto-spin-active',!!Slot.State.autoSpin);spin.addEventListener('pointerdown',event=>{longPress=false;UI.pressStandalone(spin,'spin');spin.setPointerCapture?.(event.pointerId);if(Slot.State.autoSpin){Slot.State.autoSpin=false;longPress=true;sync();return;}timer=setTimeout(()=>{longPress=true;Slot.State.autoSpin=true;sync();if(!Slot.State.isSpinning)Slot.Game.requestSpin();},Math.max(250,Number(Slot.Config.autoSpin?.holdDurationMs)||500));});const release=()=>{clearTimeout(timer);timer=null;if(!longPress)setTimeout(()=>Slot.Game.requestSpin(),Math.max(0,Number(Slot.Config.spin.buttonActionDelayMs)||0));};spin.addEventListener('pointerup',release);spin.addEventListener('pointercancel',()=>clearTimeout(timer));spin.addEventListener('contextmenu',event=>event.preventDefault());window.addEventListener('keydown',event=>{if(Slot.State.isSpinning||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(event.code==='Space'||event.code==='Enter'||event.code==='NumpadEnter')UI.pressStandalone(spin,'spin');},{capture:true});sync();};

  UI.bind=function(){document.addEventListener('click',e=>{if(e.target.closest('button'))Slot.Audio.click();},true);const spin=document.getElementById('spin-button');spin.addEventListener('pointerdown',()=>{UI.pressStandalone(spin,'spin');});spin.addEventListener('click',()=>setTimeout(()=>Slot.Game.requestSpin(),Slot.Config.spin.buttonActionDelayMs));const minus=document.getElementById('bet-minus'),plus=document.getElementById('bet-plus');minus.addEventListener('pointerdown',()=>{UI.pressPanel('betMinus',minus);});plus.addEventListener('pointerdown',()=>{UI.pressPanel('betPlus',plus);});minus.addEventListener('click',()=>Slot.Game.changeBet(-1));plus.addEventListener('click',()=>Slot.Game.changeBet(1));const leaderboard=document.getElementById('leaderboard');leaderboard.addEventListener('pointerdown',()=>{UI.pressPanel('leaderboard',leaderboard);});leaderboard.addEventListener('click',()=>UI.showPopup('LEADERBOARD','','PLACEHOLDER — ADD YOUR LOGIC LATER',1300));const cash=document.getElementById('cashout-button');cash.addEventListener('pointerdown',()=>{UI.pressStandalone(cash,'cashout');});cash.addEventListener('click',()=>UI.showPopup('CASH OUT','','PLACEHOLDER — ADD YOUR LOGIC LATER',1300));const pays=document.getElementById('pays-button');pays.addEventListener('pointerdown',()=>{UI.pressStandalone(pays,'pays');});pays.addEventListener('click',UI.showPaytable);document.getElementById('paytable-close').addEventListener('click',UI.hidePaytable);document.getElementById('paytable-layer').addEventListener('pointerdown',e=>{if(e.target.id==='paytable-layer')UI.hidePaytable();});window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.code==='Escape'&&document.getElementById('paytable-layer').classList.contains('show')){UI.hidePaytable();return;}if((e.code==='Space'||e.code==='Enter'||e.code==='NumpadEnter')&&!Slot.State.isSpinning){e.preventDefault();Slot.Audio.click();UI.pressStandalone(spin,'spin');setTimeout(()=>Slot.Game.requestSpin(),Slot.Config.spin.buttonActionDelayMs);}});document.addEventListener('pointerdown',Slot.Audio.unlock,{once:true});};
})();
