(function () {
  'use strict';
  const Slot=window.Slot;
  const A=Slot.Animation={running:false,lastTime:0,spinSequence:0};
  A.coinFlightActive=false;A.coinFlightSpeed=1;
  A.beginCoinFlight=function(){A.coinFlightActive=true;A.coinFlightSpeed=1;};
  A.endCoinFlight=function(){A.coinFlightActive=false;A.coinFlightSpeed=1;};
  A.coinAnimate=function(el,keyframes,options){const anim=el.animate(keyframes,options);if(A.coinFlightSpeed>1)anim.playbackRate=A.coinFlightSpeed;return anim;};
  A.waitAnimation=function(anim,duration){const ms=Math.max(50,Number(duration)||300);return Promise.race([anim.finished.catch(()=>{}),Slot.Utils.delay(ms+250)]).finally(()=>{try{if(anim.playState!=='finished')anim.finish();}catch(_){}});};
  A.speedUpCoinFlights=function(){if(!A.coinFlightActive||A.coinFlightSpeed>=2)return false;A.coinFlightSpeed=2;document.getAnimations().forEach(anim=>{try{anim.updatePlaybackRate(2);}catch(_){anim.playbackRate=2;}});return true;};
  window.addEventListener('pointerdown',()=>A.speedUpCoinFlights(),{capture:true});
  window.addEventListener('keydown',event=>{if(event.ctrlKey||event.altKey||event.metaKey||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(A.speedUpCoinFlights())event.preventDefault();},{capture:true});

  A.startLoop=function(){if(A.running)return;A.running=true;const tick=now=>{const active=Slot.Rendering.reels.some(reel=>reel.isSpinning);if(active){if(!A.lastTime)A.lastTime=now;const dt=Math.min(34,now-A.lastTime);A.lastTime=now;Slot.Rendering.reels.forEach(reel=>{if(reel.isSpinning)reel.position+=reel.speed*dt;});Slot.Rendering.renderReelPositions();}else A.lastTime=0;requestAnimationFrame(tick);};requestAnimationFrame(tick);};
  function animatePosition(reel,from,to,duration,easingFn){return new Promise(resolve=>{const start=performance.now();const tick=now=>{const t=Math.min(1,(now-start)/Math.max(1,duration));const e=easingFn?easingFn(t):t;reel.position=from+(to-from)*e;Slot.Rendering.renderReelPositions();if(t<1)requestAnimationFrame(tick);else resolve();};requestAnimationFrame(tick);});}

  A.stopReel=async function(reel,targetColumn,hooks={}){
    const slot=Number(Slot.Config.reels.cellHeight),speed=Math.max(.1,Number(reel.speed||Slot.Config.spin.speedPxPerMs)||2.5),leadCells=Math.max(1,Math.round(Number(Slot.Config.spin.stopLeadCells)||3));
    const rem=Slot.Utils.mod(reel.position,slot),nextSnap=reel.position+(rem<.001?slot:(slot-rem)),finalPosition=Math.round(nextSnap+leadCells*slot);
    const landingIndices=Slot.Rendering.installColumnAtPosition(reel,finalPosition,targetColumn,true);
    const startPosition=reel.position;reel.isSpinning=false;const bounce=Math.max(0,Number(Slot.Config.spin.bounceAmountPx)||0),travelTarget=finalPosition+bounce,travelDistance=Math.max(1,travelTarget-startPosition),travelDuration=travelDistance/speed,settleDuration=bounce>=.5?Math.max(60,Number(Slot.Config.spin.bounceDurationMs)||257):0;
    let leadTimer=null;const effectLead=Math.max(0,Number(Slot.Config.landingEffects?.leadTimeMs)||0);
    if(hooks.onEffectLead){leadTimer=setTimeout(()=>{try{hooks.onEffectLead(landingIndices);}catch(e){console.warn(e);}},Math.max(0,travelDuration-effectLead));}
    if(hooks.onStopAudioLead){const audioLead=Math.max(0,Number(Slot.Config.audio?.reelStopSfxLeadMs)||0);setTimeout(()=>{try{hooks.onStopAudioLead();}catch(e){console.warn(e);}},Math.max(0,travelDuration+settleDuration-audioLead));}
    await animatePosition(reel,startPosition,travelTarget,travelDuration,t=>t);
    if(leadTimer&&travelDuration-effectLead<0)clearTimeout(leadTimer);
    try{hooks.onLanding?.();}catch(e){console.warn(e);}
    if(bounce>=.5){await animatePosition(reel,travelTarget,finalPosition,settleDuration,t=>1-Math.pow(1-t,3));}else{reel.position=finalPosition;Slot.Rendering.renderReelPositions();}
    reel.position=finalPosition;reel.lockedCellIndices?.clear();Slot.Rendering.renderReelPositions();
  };

  A.animateLandingSpecials=function(reelIndex,indicesOverride=null){const reel=Slot.Rendering.reels[reelIndex];if(!reel)return Promise.resolve();const indices=indicesOverride||Slot.Rendering.visibleIndicesAt(reel,reel.position),jobs=[];let freeSpinLanded=false;indices.forEach(idx=>{const cell=reel.cells[idx];if(!cell)return;if(cell.data?.symbolId==='collect')jobs.push(A.collectLandingGlow(cell));if(cell.data?.symbolId==='freeSpins'){freeSpinLanded=true;jobs.push(A.freeSpinsLandingPop(cell));}});return Promise.all(jobs);};
  A.collectLandingGlow=function(cell){const cfg=Slot.Config.landingEffects,img=cell?.img;if(!img)return Promise.resolve();const color=cfg.collectGlowColor||'#ffe884',blur=Math.max(0,Number(cfg.collectGlowBlurPx)||0),duration=Math.max(50,Number(cfg.collectGlowDurationMs)||430),base=img.style.transform||'scale(1)',frames=Slot.Utils.isIOSWebKit?[{opacity:1,transform:base},{offset:.38,opacity:.86,transform:`${base} scale(1.035)`},{opacity:1,transform:base}]:[{filter:'brightness(1) drop-shadow(0 0 0 transparent)'},{offset:.38,filter:`brightness(1.32) drop-shadow(0 0 ${blur}px ${color})`},{filter:'brightness(1) drop-shadow(0 0 0 transparent)'}];const anim=img.animate(frames,{duration,easing:'ease-out'});return A.waitAnimation(anim,duration);};
  A.freeSpinsLandingPop=function(cell){const cfg=Slot.Config.landingEffects,img=cell?.img;if(!img)return Promise.resolve();const base=img.style.transform||'scale(1)',pop=Math.max(1,Number(cfg.freeSpinsPopScale)||1.12),duration=Math.max(80,Number(cfg.freeSpinsPopDurationMs)||360);const anim=img.animate([{transform:base},{offset:.42,transform:`${base} scale(${pop})`},{transform:base}],{duration,easing:'cubic-bezier(.2,.85,.25,1)'});return anim.finished.catch(()=>{});};

  A.spin=async function(outcome,hooks={}){const seq=++A.spinSequence,reels=Slot.Rendering.reels,ac=Slot.Config.anticipation||{};Slot.Rendering.cancelPaylineReplay();const scatters=outcome.slice(0,3).map(col=>col.some(cell=>cell?.symbolId==='freeSpins')),dollarTotal=outcome.slice(0,3).flat().reduce((sum,c)=>sum+(c?.symbolId==='dollar'?Number(c.creditMultiplier)||0:0),0),anticipated=!outcome.suppressAnticipation&&!!ac.enabled&&dollarTotal>=Number(ac.thresholdBetMultiplier||20),extra=anticipated?Math.max(0,Number(ac.extraDurationMs)||0):0,luckExtra=Math.max(0,Number(outcome.luckExtraMs)||0),ant=document.getElementById('reel4-anticipation');ant?.classList.remove('active');reels.forEach(reel=>{reel.lockedCellIndices?.clear();reel.isSpinning=true;reel.speed=Number(Slot.Config.spin.speedPxPerMs)||3.8;});const base4=Number(Slot.Config.spin.firstReelStopDelayMs)+3*Number(Slot.Config.spin.reelStopIntervalMs);let antTimer=null;if(anticipated&&extra>0)antTimer=setTimeout(()=>{if(seq===A.spinSequence){ant?.classList.add('active');hooks.onAnticipation?.();}},Math.max(0,base4));const stops=reels.map((reel,i)=>new Promise(resolve=>{const delay=Number(Slot.Config.spin.firstReelStopDelayMs)+i*Number(Slot.Config.spin.reelStopIntervalMs)+(i===3?extra:0)+luckExtra;setTimeout(async()=>{if(seq!==A.spinSequence)return resolve();await A.stopReel(reel,outcome[i],{onEffectLead:indices=>A.animateLandingSpecials(i,indices),onStopAudioLead:()=>hooks.onReelStopAudio?.(i),onLanding:()=>{if(i===3&&outcome[i].some(cell=>cell?.symbolId==='collect'))Slot.Audio.collectLand();if(outcome[i].some(cell=>cell?.symbolId==='dollar'))Slot.Audio.dollarLand();if(scatters[i]&&(i===0||(i===1&&scatters[0])||(i===2&&scatters[0]&&scatters[1])))Slot.Audio.freeSpinLand(i);hooks.onReelLanding?.(i);}});if(i===3)ant?.classList.remove('active');hooks.onReelStopped?.(i);resolve();},Math.max(0,delay));}));await Promise.all(stops);clearTimeout(antTimer);ant?.classList.remove('active');await Slot.Utils.delay(Slot.Config.spin.postStopEvaluationDelayMs);hooks.onComplete?.();};

  A.bumpCollect=function(collectCell){const img=collectCell?.img;if(!img)return Promise.resolve();const cfg=Slot.Config.collectAnimation,base=img.style.transform||'scale(1)',scale=Math.max(1,Number(cfg.collectBumpScale)||1.07),duration=Math.max(60,Number(cfg.collectBumpDurationMs)||180);const anim=img.animate([{transform:base},{offset:.35,transform:`${base} scale(${scale})`},{transform:base}],{duration,easing:'cubic-bezier(.15,.9,.2,1)'});return anim.finished.catch(()=>{});};
  A.coinSplash=function(x,y){const layer=document.getElementById('coin-flight-layer'),cfg=Slot.Config.collectAnimation,count=Math.max(0,Math.round(Number(cfg.splashCoinCount)||0)),spread=Math.max(5,Number(cfg.splashSpreadPx)||78),duration=Math.max(100,Number(cfg.splashDurationMs)||430),size=Math.max(3,Number(cfg.splashCoinSizePx)||12);for(let i=0;i<count;i++){const coin=document.createElement('i');coin.className='coin-splash-particle';coin.style.left=`${x-size/2}px`;coin.style.top=`${y-size/2}px`;coin.style.width=`${size}px`;coin.style.height=`${size}px`;layer.appendChild(coin);const angle=(-Math.PI*.85)+(Math.random()*Math.PI*1.7),dist=spread*(.45+Math.random()*.55),dx=Math.cos(angle)*dist,dy=Math.sin(angle)*dist-spread*.25;const anim=coin.animate([{transform:'translate3d(0,0,0) rotateY(0deg)',opacity:1},{offset:.65,opacity:1},{transform:`translate3d(${dx}px,${dy}px,0) rotateY(${360+Math.random()*360}deg)`,opacity:0}],{duration:duration*(.78+Math.random()*.35),easing:'cubic-bezier(.15,.7,.25,1)'});anim.finished.catch(()=>{}).finally(()=>coin.remove());}};
  function createCoinFlyer(sourceCell,stageRect){const sourceRect=sourceCell.dom.getBoundingClientRect(),x=(sourceRect.left-stageRect.left)/Slot.State.fitScale,y=(sourceRect.top-stageRect.top)/Slot.State.fitScale,w=sourceRect.width/Slot.State.fitScale,h=sourceRect.height/Slot.State.fitScale,flyer=document.createElement('div');flyer.className='flying-coin';flyer.style.left=`${x}px`;flyer.style.top=`${y}px`;flyer.style.width=`${w}px`;flyer.style.height=`${h}px`;flyer.append(sourceCell.img.cloneNode(true),sourceCell.credit.cloneNode(true));document.getElementById('coin-flight-layer').appendChild(flyer);return{flyer,x,y,w,h};}
  A.animateCollect=async function(grid,collectReelRow){const coins=Slot.GameMath.collectAmount(grid,Slot.State.bet).coins;if(!coins.length)return;const collectCell=Slot.Rendering.findVisibleCellElement(3,collectReelRow);if(!collectCell)return;A.beginCoinFlight();const stageRect=document.getElementById('game-stage').getBoundingClientRect(),cfg=Slot.Config.collectAnimation;
    const prepared=coins.map(coin=>{const sourceCell=Slot.Rendering.findVisibleCellElement(coin.reel,coin.row);return sourceCell?{sourceCell,...createCoinFlyer(sourceCell,stageRect)}:null;}).filter(Boolean);prepared.forEach(p=>p.flyer.style.visibility='hidden');
    for(let idx=0;idx<prepared.length;idx++){const {sourceCell,flyer,x,y,w,h}=prepared[idx];sourceCell.dom.classList.add('collect-source-empty');flyer.style.visibility='visible';const lift=Math.max(0,Number(cfg.liftPx)||0),liftDuration=Math.max(1,Number(cfg.liftDurationMs)||1);await A.coinAnimate(flyer,[{transform:'translate3d(0,0,0)',opacity:1},{transform:`translate3d(0,-${lift}px,0)`,opacity:1}],{duration:liftDuration,easing:'cubic-bezier(.18,.82,.25,1)',fill:'forwards'}).finished.catch(()=>{});const targetRect=collectCell.dom.getBoundingClientRect(),targetX=(targetRect.left+targetRect.width/2-stageRect.left)/Slot.State.fitScale,targetY=(targetRect.top+targetRect.height/2-stageRect.top)/Slot.State.fitScale,centerX=x+w/2,centerY=y+h/2-lift,dx=targetX-centerX,dy=targetY-centerY,flyDuration=Math.max(1,Number(cfg.flyDurationMs)||1);await A.coinAnimate(flyer,[{transform:`translate3d(0,-${lift}px,0)`,opacity:1},{offset:.84,transform:`translate3d(${dx*.86}px,${-lift+dy*.86}px,0)`,opacity:1},{transform:`translate3d(${dx}px,${-lift+dy}px,0)`,opacity:1}],{duration:flyDuration,easing:'cubic-bezier(.28,.02,.28,1)',fill:'forwards'}).finished.catch(()=>{});flyer.remove();Slot.Audio.coinCollect();A.coinSplash(targetX,targetY);Slot.Audio.collectPing(idx);await A.bumpCollect(collectCell);if(Number(cfg.staggerMs)>0)await Slot.Utils.delay(Number(cfg.staggerMs)/A.coinFlightSpeed);}A.endCoinFlight();
  };

  A.bumpPig=function(){const img=document.querySelector('#pig-graphic img'),cfg=Slot.Config.pig;if(!img)return Promise.resolve();const s=Math.max(1,Number(cfg.bumpScale)||1.08),d=Math.max(40,Number(cfg.bumpDurationMs)||180);return img.animate([{transform:'translate3d(0,0,0) scale(1)'},{offset:.38,transform:`translate3d(-8px,3px,0) scale(${s})`},{transform:'translate3d(0,0,0) scale(1)'}],{duration:d,easing:'cubic-bezier(.15,.9,.2,1)'}).finished.catch(()=>{});};
  A.animateCoinsToPig=async function(grid){const cfg=Slot.Config.pig||{},coins=[];grid.slice(0,3).forEach((col,reel)=>col.forEach((c,row)=>{if(c?.symbolId==='dollar')coins.push({reel,row});}));if(!cfg.enabled||!coins.length)return;const pig=document.getElementById('pig-graphic'),stage=document.getElementById('game-stage'),stageRect=stage.getBoundingClientRect(),pigRect=pig.getBoundingClientRect(),targetX=(pigRect.left+pigRect.width*(Number(cfg.impactXPercent)||0)/100-stageRect.left)/Slot.State.fitScale,targetY=(pigRect.top+pigRect.height*(Number(cfg.impactYPercent)||0)/100-stageRect.top)/Slot.State.fitScale;const prepared=coins.map(c=>{const sourceCell=Slot.Rendering.findVisibleCellElement(c.reel,c.row);return sourceCell?{sourceCell,...createCoinFlyer(sourceCell,stageRect)}:null;}).filter(Boolean);prepared.forEach(p=>p.flyer.style.visibility='hidden');for(let i=0;i<prepared.length;i++){const {sourceCell,flyer,x,y,w,h}=prepared[i];sourceCell.dom.classList.add('collect-source-empty');flyer.style.visibility='visible';const lift=Math.max(0,Number(cfg.liftPx)||0),ld=Math.max(20,Number(cfg.liftDurationMs)||20);{const anim=A.coinAnimate(flyer,[{transform:'translate3d(0,0,0)',opacity:1},{transform:`translate3d(0,-${lift}px,0)`,opacity:1}],{duration:ld,easing:'ease-out',fill:'forwards'});await A.waitAnimation(anim,ld);}const dx=targetX-(x+w/2),dy=targetY-(y+h/2),arc=Number(cfg.pathArcPx)||0,d=Math.max(50,Number(cfg.flyDurationMs)||50);{const anim=A.coinAnimate(flyer,[{transform:`translate3d(0,-${lift}px,0)`,opacity:1},{offset:.5,transform:`translate3d(${dx*.5}px,${dy*.5-lift-arc}px,0)`,opacity:1},{transform:`translate3d(${dx}px,${dy}px,0)`,opacity:1}],{duration:d,easing:'cubic-bezier(.24,.02,.3,1)',fill:'forwards'});await A.waitAnimation(anim,d);}flyer.remove();await A.bumpPig();if(Number(cfg.staggerMs)>0)await Slot.Utils.delay(Number(cfg.staggerMs)/A.coinFlightSpeed);}if(Math.random()<Slot.Utils.clamp(Number(cfg.growthChance)||0,0,1)){const layout=Slot.Config.layout.pigGraphic,oldFactor=Math.max(1,Number(cfg.currentGrowthScale)||1),max=Math.max(1,Number(cfg.maxScale)||4),nextFactor=Math.min(max,oldFactor*(1+Math.max(0,Number(cfg.growthStep)||.2)));if(nextFactor>oldFactor){const base=Number(layout.scale)||1,d=Math.max(80,Number(cfg.growthDurationMs)||520);await pig.animate([{transform:`scaleX(-1) scale(${base*oldFactor})`},{offset:.42,transform:`scaleX(-1) scale(${base*Math.min(max,nextFactor*1.08)}) rotate(-2deg)`},{transform:`scaleX(-1) scale(${base*nextFactor})`}],{duration:d,easing:'cubic-bezier(.18,.9,.25,1)',fill:'forwards'}).finished.catch(()=>{});cfg.currentGrowthScale=nextFactor;pig.style.transform=`scale(${base*nextFactor})`;Slot.Editor?.refreshValues?.();}}};
  // V6 pig effects keep every transform relative to the pig's current growth.
  A.bumpPig=function(){const img=document.querySelector('#pig-graphic img'),cfg=Slot.Config.pig;if(!img)return Promise.resolve();const base=Math.max(1,Number(cfg.currentGrowthScale)||1),bump=Math.max(1,Number(cfg.bumpScale)||1.08),d=Math.max(40,Number(cfg.bumpDurationMs)||180);const anim=img.animate([{transform:`translate3d(0,0,0) scaleX(-1) scale(${base})`},{offset:.38,transform:`translate3d(-8px,3px,0) scaleX(-1) scale(${base*bump})`},{transform:`translate3d(0,0,0) scaleX(-1) scale(${base})`}],{duration:d,easing:'cubic-bezier(.15,.9,.2,1)'});return anim.finished.catch(()=>{}).finally(()=>{img.style.transform=`scaleX(-1) scale(${base})`;});};

  A.growPig=async function(force=false){const cfg=Slot.Config.pig,img=document.querySelector('#pig-graphic img');if(!img)return false;if(!force&&Math.random()>=Slot.Utils.clamp(Number(cfg.growthChance)||0,0,1))return false;const oldScale=Math.max(1,Number(cfg.currentGrowthScale)||1),max=Math.max(1,Number(cfg.maxScale)||4),next=Math.min(max,oldScale>=3&&max>3?max:oldScale*(1+Math.max(0,Number(cfg.growthStep)||.2)));if(next<=oldScale+.0001)return false;const d=Math.max(80,Number(cfg.growthDurationMs)||520);await img.animate([{transform:`scaleX(-1) scale(${oldScale})`},{offset:.42,transform:`scaleX(-1) scale(${Math.min(max,next*1.08)}) rotate(-2deg)`},{transform:`scaleX(-1) scale(${next})`}],{duration:d,easing:'cubic-bezier(.18,.9,.25,1)',fill:'forwards'}).finished.catch(()=>{});cfg.currentGrowthScale=next;img.style.transform=`scaleX(-1) scale(${next})`;Slot.Editor?.refreshValues?.();return true;};

  A.runPigBurst=async function(){const cfg=Slot.Config.pig,pig=document.getElementById('pig-graphic'),img=pig.querySelector('img'),stage=document.getElementById('game-stage'),reels=document.getElementById('reels'),stageRect=stage.getBoundingClientRect(),pigRect=pig.getBoundingClientRect(),reelRect=reels.getBoundingClientRect(),fit=Slot.State.fitScale||1,dx=(reelRect.left+reelRect.width/2-(pigRect.left+pigRect.width/2))/fit,dy=(reelRect.top+reelRect.height/2-(pigRect.top+pigRect.height/2))/fit,base=Number(Slot.Config.layout.pigGraphic.scale)||1,flyMs=Math.max(100,Number(cfg.burstFlyDurationMs)||850);pig.style.visibility='visible';await pig.animate([{transform:`translate3d(0,0,0) scale(${base})`},{transform:`translate3d(${dx}px,${dy}px,0) scale(${base})`}],{duration:flyMs,easing:'cubic-bezier(.2,.72,.2,1)',fill:'forwards'}).finished.catch(()=>{});const centerX=(reelRect.left+reelRect.width/2-stageRect.left)/fit,centerY=(reelRect.top+reelRect.height/2-stageRect.top)/fit,layer=document.getElementById('coin-flight-layer'),count=Math.max(0,Math.round(Number(cfg.burstCoinCount)||0)),spread=Math.max(20,Number(cfg.burstSpreadPx)||300),duration=Math.max(100,Number(cfg.burstExplosionDurationMs)||650);for(let i=0;i<count;i++){const coin=document.createElement('img');coin.className='pig-burst-coin';coin.src=Slot.Utils.cacheUrl(Slot.Config.symbols.dollar.image);coin.style.left=`${centerX-60}px`;coin.style.top=`${centerY-60}px`;layer.appendChild(coin);const angle=Math.random()*Math.PI*2,dist=spread*(.35+Math.random()*.65),x=Math.cos(angle)*dist,y=Math.sin(angle)*dist;coin.animate([{transform:'translate3d(0,0,0) rotate(0deg) scale(.45)',opacity:0},{offset:.12,opacity:1},{offset:.72,opacity:1},{transform:`translate3d(${x}px,${y}px,0) rotate(${360+Math.random()*540}deg) scale(1)`,opacity:0}],{duration:duration*(.75+Math.random()*.45),easing:'cubic-bezier(.12,.72,.25,1)'}).finished.catch(()=>{}).finally(()=>coin.remove());}const growth=Math.max(1,Number(cfg.currentGrowthScale)||1);await img.animate([{transform:`scaleX(-1) scale(${growth})`,opacity:1,filter:'brightness(1)'},{offset:.38,transform:`scaleX(-1) scale(${growth*1.32})`,opacity:1,filter:'brightness(2.6) drop-shadow(0 0 30px #fff59b)'},{transform:`scaleX(-1) scale(${growth*.12})`,opacity:0,filter:'brightness(4) drop-shadow(0 0 60px #ffd33d)'}],{duration,easing:'cubic-bezier(.18,.7,.2,1)',fill:'forwards'}).finished.catch(()=>{});pig.style.visibility='hidden';};

  A.restorePig=function(){const cfg=Slot.Config.pig,pig=document.getElementById('pig-graphic'),img=pig.querySelector('img'),base=Number(Slot.Config.layout.pigGraphic.scale)||1;pig.getAnimations().forEach(a=>a.cancel());img.getAnimations().forEach(a=>a.cancel());cfg.currentGrowthScale=1;pig.style.visibility='visible';pig.style.transform=`scale(${base})`;img.style.opacity='1';img.style.filter='';img.style.transform='scaleX(-1) scale(1)';Slot.Editor?.refreshValues?.();};

  A.animateCoinsToPig=async function(grid){const cfg=Slot.Config.pig||{},coins=[];grid.slice(0,3).forEach((col,reel)=>col.forEach((c,row)=>{if(c?.symbolId==='dollar')coins.push({reel,row});}));if(!cfg.enabled||!coins.length)return{grew:false,burstTriggered:false};A.beginCoinFlight();const pig=document.getElementById('pig-graphic'),stage=document.getElementById('game-stage'),stageRect=stage.getBoundingClientRect(),pigRect=pig.getBoundingClientRect(),targetX=(pigRect.left+pigRect.width*(Number(cfg.impactXPercent)||0)/100-stageRect.left)/Slot.State.fitScale,targetY=(pigRect.top+pigRect.height*(Number(cfg.impactYPercent)||0)/100-stageRect.top)/Slot.State.fitScale,prepared=coins.map(c=>{const sourceCell=Slot.Rendering.findVisibleCellElement(c.reel,c.row);return sourceCell?{sourceCell,...createCoinFlyer(sourceCell,stageRect)}:null;}).filter(Boolean);prepared.forEach(p=>p.flyer.style.visibility='hidden');for(let i=0;i<prepared.length;i++){const {sourceCell,flyer,x,y,w,h}=prepared[i];sourceCell.dom.classList.add('collect-source-empty');flyer.style.visibility='visible';const lift=Math.max(0,Number(cfg.liftPx)||0),ld=Math.max(20,Number(cfg.liftDurationMs)||20);{const anim=A.coinAnimate(flyer,[{transform:'translate3d(0,0,0)',opacity:1},{transform:`translate3d(0,-${lift}px,0)`,opacity:1}],{duration:ld,easing:'ease-out',fill:'forwards'});await A.waitAnimation(anim,ld);}const dx=targetX-(x+w/2),dy=targetY-(y+h/2),arc=Number(cfg.pathArcPx)||0,d=Math.max(50,Number(cfg.flyDurationMs)||50);{const anim=A.coinAnimate(flyer,[{transform:`translate3d(0,-${lift}px,0)`,opacity:1},{offset:.5,transform:`translate3d(${dx*.5}px,${dy*.5-lift-arc}px,0)`,opacity:1},{transform:`translate3d(${dx}px,${dy}px,0)`,opacity:1}],{duration:d,easing:'cubic-bezier(.24,.02,.3,1)',fill:'forwards'});await A.waitAnimation(anim,d);}flyer.remove();await A.bumpPig();if(Number(cfg.staggerMs)>0)await Slot.Utils.delay(Number(cfg.staggerMs)/A.coinFlightSpeed);}A.endCoinFlight();const grew=await A.growPig(false),atMaximum=Number(cfg.currentGrowthScale)>=Number(cfg.maxScale),burstTriggered=(grew||atMaximum)&&Math.random()<Slot.Utils.clamp(Number(cfg.burstChanceAfterGrowth)||0,0,1);if(burstTriggered)await A.runPigBurst();return{grew,burstTriggered};};
  const bumpPigWithSfx=A.bumpPig;A.bumpPig=function(){Slot.Audio.coinInPig();return bumpPigWithSfx();};
  const runPigBurstWithSfx=A.runPigBurst;A.runPigBurst=function(){window.setTimeout(()=>Slot.Audio.pigBreak(),Math.max(100,Number(Slot.Config.pig.burstFlyDurationMs)||850));return runPigBurstWithSfx();};
  // V9 burst: arrive, grow slowly to the configured maximum, then break and throw coins.
  A.runPigBurst=async function(){
    const cfg=Slot.Config.pig,pig=document.getElementById('pig-graphic'),img=pig?.querySelector('img'),stage=document.getElementById('game-stage'),reels=document.getElementById('reels');
    if(!pig||!img||!stage||!reels)return;
    const stageRect=stage.getBoundingClientRect(),pigRect=pig.getBoundingClientRect(),reelRect=reels.getBoundingClientRect(),fit=Slot.State.fitScale||1;
    const dx=(reelRect.left+reelRect.width/2-(pigRect.left+pigRect.width/2))/fit,dy=(reelRect.top+reelRect.height/2-(pigRect.top+pigRect.height/2))/fit,base=Number(Slot.Config.layout.pigGraphic.scale)||1,flyMs=Math.max(100,Number(cfg.burstFlyDurationMs)||850);
    pig.style.visibility='visible';pig.classList.add('pig-burst-active');
    try{
      let anim=pig.animate([{transform:`translate3d(0,0,0) scale(${base})`},{transform:`translate3d(${dx}px,${dy}px,0) scale(${base})`}],{duration:flyMs,easing:'cubic-bezier(.2,.72,.2,1)',fill:'forwards'});await A.waitAnimation(anim,flyMs);
      const current=Math.max(1,Number(cfg.currentGrowthScale)||1),max=Math.max(current,Number(cfg.maxScale)||4),growMs=Math.max(100,Number(cfg.burstMaxGrowDurationMs)||1200);
      anim=img.animate([{transform:`translate3d(0,0,0) scaleX(-1) scale(${current})`,opacity:1},{transform:`translate3d(0,0,0) scaleX(-1) scale(${max})`,opacity:1}],{duration:growMs,easing:'cubic-bezier(.18,.72,.2,1)',fill:'forwards'});await A.waitAnimation(anim,growMs);
      cfg.currentGrowthScale=max;img.style.transform=`translate3d(0,0,0) scaleX(-1) scale(${max})`;Slot.Editor?.refreshValues?.();
      await Slot.Utils.delay(Math.max(0,Number(cfg.burstMaxHoldMs)||0));Slot.Audio.pigBreak();
      const centerX=(reelRect.left+reelRect.width/2-stageRect.left)/fit,centerY=(reelRect.top+reelRect.height/2-stageRect.top)/fit,layer=document.getElementById('coin-flight-layer');
      const rawCount=Math.max(0,Math.round(Number(cfg.burstCoinCount)||0)),count=Slot.Utils.isIOSWebKit?Math.min(rawCount,18):rawCount,spread=Math.max(20,Number(cfg.burstSpreadPx)||300),duration=Math.max(100,Number(cfg.burstExplosionDurationMs)||650);
      for(let i=0;i<count;i++){
        const coin=document.createElement('img');coin.className='pig-burst-coin';coin.src=Slot.Utils.cacheUrl(Slot.Config.symbols.dollar.image);coin.style.left=`${centerX-60}px`;coin.style.top=`${centerY-60}px`;layer.appendChild(coin);
        const angle=Math.random()*Math.PI*2,dist=spread*(.35+Math.random()*.65),x=Math.cos(angle)*dist,y=Math.sin(angle)*dist;
        const ca=coin.animate([{transform:'translate3d(0,0,0) rotate(0deg) scale(.45)',opacity:0},{offset:.12,opacity:1},{offset:.72,opacity:1},{transform:`translate3d(${x}px,${y}px,0) rotate(${360+Math.random()*540}deg) scale(1)`,opacity:0}],{duration:duration*(.75+Math.random()*.45),easing:'cubic-bezier(.12,.72,.25,1)'});
        A.waitAnimation(ca,duration*1.25).finally(()=>coin.remove());
      }
      const burstFrames=Slot.Utils.isIOSWebKit?[{transform:`translate3d(0,0,0) scaleX(-1) scale(${max})`,opacity:1},{offset:.38,transform:`translate3d(0,0,0) scaleX(-1) scale(${max*1.08})`,opacity:.9},{transform:`translate3d(0,0,0) scaleX(-1) scale(${max*.12})`,opacity:0}]:[{transform:`scaleX(-1) scale(${max})`,opacity:1,filter:'brightness(1)'},{offset:.38,transform:`scaleX(-1) scale(${max*1.12})`,opacity:1,filter:'brightness(2.6) drop-shadow(0 0 30px #fff59b)'},{transform:`scaleX(-1) scale(${max*.12})`,opacity:0,filter:'brightness(4) drop-shadow(0 0 60px #ffd33d)'}];
      anim=img.animate(burstFrames,{duration,easing:'cubic-bezier(.18,.7,.2,1)',fill:'forwards'});await A.waitAnimation(anim,duration);pig.style.visibility='hidden';
    }finally{pig.classList.remove('pig-burst-active');}
  };
})();
