(function () {
  'use strict';
  const Slot=window.Slot;
  const R=Slot.Rendering={reels:[],paylineTimer:null,lastPaylineWins:[],paylineReplaySequence:0};
  const imageUrlFor=id=>Slot.Utils.cacheUrl(Slot.Config.symbols[id].image);

  R.applyArtwork=function(){
    const betUrl=Slot.Utils.cacheUrl(Slot.Config.artwork.betPanel);
    document.querySelectorAll('#bet-panel .panel-art').forEach(img=>img.src=betUrl);
    const cashUrl=Slot.Utils.cacheUrl(Slot.Config.artwork.cashoutButton);
    document.querySelector('#cashout-button img').src=cashUrl;
    document.getElementById('cashout-button').style.setProperty('--art-mask',`url("${cashUrl}")`);
    const spinUrl=Slot.Utils.cacheUrl(Slot.Config.artwork.spinButton);
    document.querySelectorAll('#spin-button img').forEach(img=>img.src=spinUrl);
    document.getElementById('spin-button').style.setProperty('--art-mask',`url("${spinUrl}")`);
    document.getElementById('spin-button').style.setProperty('--art-image',`url("${spinUrl}")`);
    const featureImg=document.getElementById('free-spins-feature-symbol');
    if(featureImg) featureImg.src=imageUrlFor('freeSpins');
    const pig=document.querySelector('#pig-graphic img');
    if(pig) pig.src=Slot.Utils.cacheUrl(Slot.Config.pig.image);
  };

  R.createReels=function(){
    const host=document.getElementById('reels'); host.innerHTML=''; R.reels=[];
    const {count,rows,reelWidth,cellHeight,symbolBufferCells}=Slot.Config.reels;
    host.style.width=`${count*reelWidth}px`;host.style.height=`${rows*cellHeight}px`;host.style.backgroundColor=Slot.Config.reels.backgroundColor;
    for(let i=0;i<count;i++){
      const reelEl=document.createElement('div');reelEl.className='reel';reelEl.dataset.reel=String(i);reelEl.style.width=`${reelWidth}px`;reelEl.style.height=`${rows*cellHeight}px`;reelEl.style.backgroundColor=Slot.Config.reels.backgroundColor;reelEl.style.borderRightColor=Slot.Config.reels.dividerColor;host.appendChild(reelEl);
      const reel={index:i,element:reelEl,cells:[],position:0,speed:0,isSpinning:false,lockedCellIndices:new Set()};
      for(let j=0;j<symbolBufferCells;j++){
        const dom=document.createElement('div');dom.className='symbol-cell';dom.style.width=`${reelWidth}px`;dom.style.height=`${cellHeight}px`;
        const img=document.createElement('img');img.className='symbol-art';img.alt='';
        const credit=document.createElement('span');credit.className='credit-value';dom.append(img,credit);reelEl.appendChild(dom);
        const data=Slot.ReelOutcomes.randomCellForReel(i);const cell={dom,img,credit,data};reel.cells.push(cell);R.applyCellData(cell,data);
      }
      R.reels.push(reel);
    }
    R.renderReelPositions();R.resizePaylineLayer();
  };

  R.applyCellData=function(cell,data){
    cell.data=data;const cfg=Slot.Config.symbols[data.symbolId];cell.dom.dataset.symbol=data.symbolId;cell.dom.classList.toggle('is-dollar',data.symbolId==='dollar');cell.dom.classList.remove('collect-source-empty');
    if(cell.img.dataset.symbolId!==data.symbolId){cell.img.src=imageUrlFor(data.symbolId);cell.img.dataset.symbolId=data.symbolId;}
    const pad=Number(cfg.cellPadding)||0;cell.img.style.maxWidth=`calc(100% - ${pad*2}px)`;cell.img.style.maxHeight=`calc(100% - ${pad*2}px)`;cell.img.style.transform=`translate(${Number(cfg.xOffset)||0}px,${Number(cfg.yOffset)||0}px) scale(${Number(cfg.scale)||1})`;cell.img.style.opacity=String(cfg.opacity??1);
    cell.credit.textContent=data.symbolId==='dollar'?`${data.creditMultiplier}x`:'';
    if(data.symbolId==='dollar')cell.credit.style.fontSize=`${Number(Slot.Config.symbols.dollar.valueFontSizePx)||34}px`;
  };
  R.refreshSymbolStyles=()=>R.reels.forEach(reel=>reel.cells.forEach(cell=>R.applyCellData(cell,cell.data)));

  R.renderReelPositions=function(){
    const slot=Number(Slot.Config.reels.cellHeight);
    R.reels.forEach(reel=>{const total=reel.cells.length*slot;reel.cells.forEach((cell,idx)=>{const y=Slot.Utils.mod(reel.position+idx*slot,total)-slot;cell.dom.style.transform=`translate3d(0,${Math.round(y)}px,0)`;if(reel.isSpinning&&y>slot*4.1&&!reel.lockedCellIndices?.has(idx)){R.applyCellData(cell,Slot.ReelOutcomes.randomCellForReel(reel.index));}})});
  };

  R.visibleIndicesAt=function(reel,position){const slot=Number(Slot.Config.reels.cellHeight),total=reel.cells.length*slot,out=[];for(let row=0;row<Slot.Config.reels.rows;row++){let best=-1,dist=Infinity;reel.cells.forEach((cell,idx)=>{const y=Slot.Utils.mod(position+idx*slot,total)-slot,d=Math.abs(y-row*slot);if(d<dist){dist=d;best=idx;}});out.push(best);}return out;};
  R.installColumnAtPosition=function(reel,position,column,lock=false){const indices=R.visibleIndicesAt(reel,position);if(lock)reel.lockedCellIndices=new Set(indices);indices.forEach((idx,row)=>R.applyCellData(reel.cells[idx],Slot.Utils.clone(column[row])));return indices;};
  R.getVisibleGrid=function(){return R.reels.map(reel=>R.visibleIndicesAt(reel,reel.position).map(i=>Slot.Utils.clone(reel.cells[i].data)));};
  R.findVisibleCellElement=function(reelIndex,row){const reel=R.reels[reelIndex];if(!reel)return null;const idx=R.visibleIndicesAt(reel,reel.position)[row];return reel.cells[idx]||null;};

  function pressVars(el,cfg){if(!el||!cfg)return;const x=Number(cfg.regionXPercent)||0,y=Number(cfg.regionYPercent)||0,w=Number(cfg.regionWidthPercent)||100,h=Number(cfg.regionHeightPercent)||100;el.style.setProperty('--button-press-duration',`${Math.max(0,Number(cfg.durationMs)||0)}ms`);el.style.setProperty('--button-press-x',`${Number(cfg.translateXPx)||0}px`);el.style.setProperty('--button-press-y',`${Number(cfg.translateYPx)||0}px`);el.style.setProperty('--button-press-scale',String(Number(cfg.scale)||1));el.style.setProperty('--button-press-brightness',String(Number(cfg.brightness)||1));el.style.setProperty('--button-press-saturation',String(Number(cfg.saturation)||1));el.style.setProperty('--button-overlay-opacity',String(Slot.Utils.clamp(Number(cfg.overlayOpacity)||0,0,1)));el.style.setProperty('--button-shadow-opacity',String(Slot.Utils.clamp(Number(cfg.shadowOpacity)||0,0,1)));el.style.setProperty('--button-shadow-blur',`${Math.max(0,Number(cfg.shadowBlurPx)||0)}px`);el.style.setProperty('--button-highlight-opacity',String(Slot.Utils.clamp(Number(cfg.highlightOpacity)||0,0,1)));el.style.setProperty('--effect-x',`${x}%`);el.style.setProperty('--effect-y',`${y}%`);el.style.setProperty('--effect-w',`${w}%`);el.style.setProperty('--effect-h',`${h}%`);el.style.setProperty('--effect-radius',`${Number(cfg.regionRadiusPercent)||0}%`);el.style.setProperty('--effect-center-x',`${x+w/2}%`);el.style.setProperty('--effect-center-y',`${y+h/2}%`);el.style.setProperty('--effect-rx',`${w/2}%`);el.style.setProperty('--effect-ry',`${h/2}%`);}
  R.applyButtonPressStyle=function(){
    const base=Slot.Config.buttonPress||{},per=Slot.Config.buttonPressByButton||{};
    const map={spin:'#spin-button',cashout:'#cashout-button',pays:'#pays-button',betMinus:'#bet-minus',betPlus:'#bet-plus',leaderboard:'#leaderboard'};
    Object.entries(map).forEach(([key,sel])=>{const cfg=per[key]||base,el=document.querySelector(sel),x=Number(cfg.regionXPercent)||0,y=Number(cfg.regionYPercent)||0,w=Number(cfg.regionWidthPercent)||100,h=Number(cfg.regionHeightPercent)||100;pressVars(el,cfg);if(['betMinus','betPlus','leaderboard'].includes(key)&&el){el.style.left=`${x}%`;el.style.top=`${y}%`;el.style.width=`${w}%`;el.style.height=`${h}%`;el.style.borderRadius=`${Number(cfg.regionRadiusPercent)||0}%`;}const layer=document.querySelector(`.panel-pressed-layer[data-segment="${key}"]`);if(layer){pressVars(layer,cfg);if(key==='betMinus'||key==='betPlus')layer.style.setProperty('clip-path',`ellipse(${w/2}% ${h/2}% at ${x+w/2}% ${y+h/2}%)`,'important');else layer.style.removeProperty('clip-path');}});
  };

  R.resizePaylineLayer=function(){const svg=document.getElementById('payline-layer');if(!svg)return;const w=Number(Slot.Config.reels.reelWidth)*4,h=Number(Slot.Config.reels.cellHeight)*3;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.style.width=`${w}px`;svg.style.height=`${h}px`;};
  R.clearPaylines=function(){clearTimeout(R.paylineTimer);const svg=document.getElementById('payline-layer');if(svg){svg.innerHTML='';svg.style.opacity='1';}};
  R.cancelPaylineReplay=function(){R.paylineReplaySequence++;R.clearPaylines();};
  R.drawPaylines=function(wins,autoClear=true){R.clearPaylines();if(!wins?.length)return;R.lastPaylineWins=Slot.Utils.clone(wins);const svg=document.getElementById('payline-layer');if(!svg)return;const ns='http://www.w3.org/2000/svg',rw=Number(Slot.Config.reels.reelWidth),ch=Number(Slot.Config.reels.cellHeight),cfg=Slot.Config.paylines||{};const colors=['#ffe45c','#ff4b4b','#8dff8a','#ffffff','#ff8cf4','#72e7ff','#ff9f43','#d3a7ff'];
    wins.forEach((win,i)=>{const pts=win.rows.map((row,reel)=>`${reel*rw+rw/2},${row*ch+ch/2}`).join(' '),color=colors[i%colors.length];const glow=document.createElementNS(ns,'polyline');glow.setAttribute('points',pts);glow.setAttribute('fill','none');glow.setAttribute('stroke',color);glow.setAttribute('stroke-width',String((Number(cfg.lineWidthPx)||5)+(Number(cfg.glowWidthPx)||10)));glow.setAttribute('opacity','0.22');glow.setAttribute('stroke-linecap','round');glow.setAttribute('stroke-linejoin','round');const line=document.createElementNS(ns,'polyline');line.setAttribute('points',pts);line.setAttribute('fill','none');line.setAttribute('stroke',color);line.setAttribute('stroke-width',String(Number(cfg.lineWidthPx)||5));line.setAttribute('opacity',String(Number(cfg.opacity)||.95));line.setAttribute('stroke-linecap','round');line.setAttribute('stroke-linejoin','round');svg.append(glow,line);});
    if(autoClear)R.paylineTimer=setTimeout(R.clearPaylines,Math.max(100,Number(cfg.displayDurationMs)||1200));
  };
  R.replayPaylines=async function(){const cfg=Slot.Config.paylineReplay||{};if(!cfg.enabled||!R.lastPaylineWins.length)return;const seq=++R.paylineReplaySequence;R.drawPaylines(R.lastPaylineWins,false);const svg=document.getElementById('payline-layer'),count=Math.max(0,Math.round(Number(cfg.repeatCount)||0));svg.classList.add('replaying');for(let i=0;i<count&&seq===R.paylineReplaySequence;i++){svg.style.opacity='0';await svg.animate([{opacity:0},{opacity:1}],{duration:Math.max(20,Number(cfg.fadeInMs)||20),fill:'forwards',easing:'ease-out'}).finished.catch(()=>{});if(seq!==R.paylineReplaySequence)break;await Slot.Utils.delay(Math.max(0,Number(cfg.holdMs)||0));if(seq!==R.paylineReplaySequence)break;await svg.animate([{opacity:1},{opacity:0}],{duration:Math.max(20,Number(cfg.fadeOutMs)||20),fill:'forwards',easing:'ease-in'}).finished.catch(()=>{});if(i<count-1)await Slot.Utils.delay(Math.max(0,Number(cfg.gapMs)||0));}if(seq===R.paylineReplaySequence){svg.classList.remove('replaying');R.clearPaylines();}};
  R.replayFreeSpinPaylines=async function(wins){const cfg=Slot.Config.freeSpinsWinPresentation||{};if(!wins?.length)return;const seq=++R.paylineReplaySequence,svg=document.getElementById('payline-layer'),count=Math.max(1,Math.round(Number(cfg.repeatCount)||5));let skipped=false;const skip=()=>{skipped=true;};if(cfg.continueOnClick!==false)window.addEventListener('pointerdown',skip,{once:true,capture:true});R.drawPaylines(wins,false);svg.classList.add('replaying');for(let i=0;i<count&&!skipped&&seq===R.paylineReplaySequence;i++){svg.style.opacity='0';await svg.animate([{opacity:0},{opacity:1}],{duration:Math.max(20,Number(cfg.fadeInMs)||20),fill:'forwards',easing:'ease-out'}).finished.catch(()=>{});if(skipped)break;await Slot.Utils.delay(Math.max(0,Number(cfg.holdMs)||0));if(skipped)break;await svg.animate([{opacity:1},{opacity:0}],{duration:Math.max(20,Number(cfg.fadeOutMs)||20),fill:'forwards',easing:'ease-in'}).finished.catch(()=>{});if(i<count-1&&!skipped)await Slot.Utils.delay(Math.max(0,Number(cfg.gapMs)||0));}window.removeEventListener('pointerdown',skip,true);if(seq===R.paylineReplaySequence){svg.classList.remove('replaying');R.clearPaylines();}};
  R.replayFreeSpinPaylines=async function(wins){const cfg=Slot.Config.freeSpinsWinPresentation||{};if(!wins?.length)return;const seq=++R.paylineReplaySequence,svg=document.getElementById('payline-layer'),count=Math.max(1,Math.round(Number(cfg.repeatCount)||5));let skipped=false,resolveSkip;const skipPromise=new Promise(resolve=>resolveSkip=resolve),skip=()=>{skipped=true;resolveSkip();},wait=ms=>Promise.race([Slot.Utils.delay(Math.max(0,Number(ms)||0)),skipPromise]),animateOrSkip=async anim=>{await Promise.race([anim.finished.catch(()=>{}),skipPromise]);if(skipped)anim.cancel();};if(cfg.continueOnClick!==false)window.addEventListener('pointerdown',skip,{once:true,capture:true});R.drawPaylines(wins,false);svg.classList.add('replaying');for(let i=0;i<count&&!skipped&&seq===R.paylineReplaySequence;i++){svg.style.opacity='0';await animateOrSkip(svg.animate([{opacity:0},{opacity:1}],{duration:Math.max(20,Number(cfg.fadeInMs)||20),fill:'forwards',easing:'ease-out'}));if(skipped)break;await wait(cfg.holdMs);if(skipped)break;await animateOrSkip(svg.animate([{opacity:1},{opacity:0}],{duration:Math.max(20,Number(cfg.fadeOutMs)||20),fill:'forwards',easing:'ease-in'}));if(i<count-1&&!skipped)await wait(cfg.gapMs);}window.removeEventListener('pointerdown',skip,true);if(seq===R.paylineReplaySequence){svg.classList.remove('replaying');R.clearPaylines();}};

  R.applyLayout=function(){const layout=Slot.Config.layout;for(const [key,cfg] of Object.entries(layout)){const el=document.querySelector(`[data-layout-key="${key}"]`);if(!el)continue;el.style.left=`${Number(cfg.x)||0}px`;el.style.top=`${Number(cfg.y)||0}px`;el.style.transform=`scale(${Number(cfg.scale)||1})`;}
    const rw=Number(Slot.Config.reels.reelWidth),ch=Number(Slot.Config.reels.cellHeight);document.getElementById('reel-frame').style.width=`${rw*4+22}px`;document.getElementById('reel-frame').style.height=`${ch*3+22}px`;document.getElementById('spin-button').style.width='538px';document.getElementById('spin-button').style.height='542px';document.getElementById('cashout-button').style.width='240px';document.getElementById('cashout-button').style.height='212px';const ant=document.getElementById('reel4-anticipation'),ac=Slot.Config.anticipation||{};ant.style.left=`${11+rw*3}px`;ant.style.top='11px';ant.style.width=`${rw}px`;ant.style.height=`${ch*3}px`;ant.style.borderWidth=`${Number(ac.borderThicknessPx)||1}px`;ant.style.borderColor=ac.borderColor||'#ffe45c';ant.style.borderRadius=`${Number(ac.borderRadiusPx)||0}px`;ant.style.boxShadow=`0 0 ${Number(ac.glowBlurPx)||0}px ${ac.glowColor||'#fff'},inset 0 0 ${Number(ac.glowBlurPx)||0}px ${ac.secondaryColor||'#f00'}`;ant.style.setProperty('--anticipation-speed',`${Number(ac.pulseDurationMs)||380}ms`);const pig=document.getElementById('pig-graphic');pig.style.display=Slot.Config.pig.enabled?'block':'none';const pigImg=pig.querySelector('img');if(pigImg)pigImg.style.transform=`scaleX(-1) scale(${Math.max(1,Number(Slot.Config.pig.currentGrowthScale)||1)})`;R.resizePaylineLayer();R.applyButtonPressStyle();};

  R.applyPopupStyle=function(){const p=Slot.Config.popup,layer=document.getElementById('popup-layer'),card=document.getElementById('popup-card'),rf=Slot.Config.layout.reelFrame||{},reelScale=Number(rf.scale)||1,rw=Number(Slot.Config.reels.reelWidth),ch=Number(Slot.Config.reels.cellHeight),centerX=(Number(rf.x)||0)+(11+rw*2)*reelScale+(Number(p.xOffsetPx)||0),centerY=(Number(rf.y)||0)+(11+ch*1.5)*reelScale+(Number(p.yOffsetPx)||0);layer.style.background=`rgba(0,0,0,${Slot.Utils.clamp(Number(p.backdropOpacity)||0,0,1)})`;layer.classList.remove('anim-pop','anim-fade','anim-slide');layer.classList.add(`anim-${p.animation||'pop'}`);card.style.position='absolute';card.style.left=`${centerX}px`;card.style.top=`${centerY}px`;card.style.translate='-50% -50%';card.style.width=`${Number(p.widthPx)||430}px`;card.style.minWidth='0';card.style.maxWidth='none';card.style.minHeight=`${Number(p.minHeightPx)||0}px`;card.style.padding=`${Number(p.paddingYPx)||0}px ${Number(p.paddingXPx)||0}px`;card.style.borderWidth=`${Number(p.borderWidthPx)||0}px`;card.style.setProperty('--popup-scale',String(Number(p.scale)||1));card.style.background=`linear-gradient(180deg,${p.backgroundColor},${p.backgroundColor2||'#003e74'})`;card.style.borderColor=p.borderColor;card.style.setProperty('--popup-accent',p.accentColor||'#fff');card.style.borderRadius=`${Number(p.borderRadiusPx)||0}px`;card.style.color=p.textColor;card.style.fontFamily=p.fontFamily||'Arial, sans-serif';card.style.fontWeight=String(Number(p.fontWeight)||900);card.style.letterSpacing=`${Number(p.letterSpacingPx)||0}px`;card.style.boxShadow=`0 15px ${Number(p.shadowBlurPx)||0}px rgba(0,0,0,.65),inset 0 0 0 2px rgba(255,255,255,.26),inset 0 -7px 0 var(--popup-accent,#cf101d)`;const title=document.getElementById('popup-title'),value=document.getElementById('popup-value'),subtitle=document.getElementById('popup-subtitle');title.style.color=p.titleColor;title.style.fontSize=`${Number(p.titleFontSizePx)||24}px`;value.style.fontSize=`${Number(p.valueFontSizePx)||64}px`;value.style.fontWeight=String(Number(p.fontWeight)||1000);subtitle.style.fontSize=`${Number(p.subtitleFontSizePx)||15}px`;};
  R.applyPaytableStyle=function(){const p=Slot.Config.paytablePopup||{},card=document.getElementById('paytable-card');if(!card)return;card.style.width=`${Number(p.widthPx)||720}px`;card.style.maxHeight=`${Number(p.maxHeightPx)||650}px`;card.style.borderRadius=`${Number(p.borderRadiusPx)||0}px`;card.style.borderWidth=`${Number(p.borderWidthPx)||0}px`;card.style.borderColor=p.borderColor||'#d9e5ee';card.style.background=`linear-gradient(180deg,${p.backgroundColor||'#0078d4'},${p.backgroundColor2||'#00477f'})`;card.style.fontFamily=p.fontFamily||'Arial, sans-serif';card.style.fontWeight=String(Number(p.fontWeight)||900);document.querySelector('.paytable-header').style.fontSize=`${Number(p.titleFontSizePx)||32}px`;document.querySelectorAll('.pay-row').forEach(row=>{row.style.minHeight=`${Number(p.rowMinHeightPx)||82}px`;const img=row.querySelector('img'),name=row.querySelector('.pay-name'),pay=row.querySelector('strong');img.style.width=img.style.height=`${Number(p.symbolSizePx)||70}px`;name.style.fontSize=`${Number(p.nameFontSizePx)||18}px`;name.style.color=p.textColor||'#fff';pay.style.fontSize=`${Number(p.payFontSizePx)||24}px`;pay.style.color=p.payColor||'#ffea75';});};
  R.applyFreeSpinsCounterStyle=function(){const c=Slot.Config.freeSpinsCounter||{},el=document.getElementById('free-spins-counter'),label=document.getElementById('free-spins-counter-label'),thumbs=document.getElementById('free-spins-counter-thumbnails');if(!el)return;el.style.gap=`${Number(c.gapPx)||0}px`;el.style.padding=`${Number(c.paddingPx)||0}px`;el.style.border=`${Number(c.borderWidthPx)||0}px solid ${c.borderColor||'#ffe884'}`;el.style.borderRadius=`${Number(c.borderRadiusPx)||0}px`;el.style.background=c.backgroundColor||'#003e74';label.style.display=c.showLabel===false?'none':'inline';label.textContent=c.labelText||'';label.style.color=c.labelColor||'#fff';label.style.fontSize=`${Number(c.labelFontSizePx)||14}px`;thumbs.style.gap=`${Number(c.gapPx)||0}px`;el.classList.toggle('show',!!c.enabled&&Slot.State.freeSpinsRemaining>0);};
  R.updateFreeSpinsCounter=function(remaining){Slot.State.freeSpinsRemaining=Math.max(0,Math.round(Number(remaining)||0));const host=document.getElementById('free-spins-counter-thumbnails'),c=Slot.Config.freeSpinsCounter||{};if(!host)return;host.innerHTML='';for(let i=0;i<Slot.State.freeSpinsRemaining;i++){const img=document.createElement('img');img.className='free-spin-thumb';img.src=imageUrlFor('dollar');img.alt='';img.style.width=img.style.height=`${Number(c.thumbnailSizePx)||26}px`;host.appendChild(img);}R.applyFreeSpinsCounterStyle();};
  R.showLuckShower=async function(){const c=Slot.Config.luckHasArrived||{},layer=document.getElementById('luck-shower'),host=document.getElementById('luck-shower-coins'),title=document.getElementById('luck-shower-title');if(!layer||!host)return;await Slot.Utils.delay(Math.max(0,Number(c.revealDelayMs)||0));Slot.Audio.coinsFalling();host.innerHTML='';layer.style.background=`rgba(0,0,0,${Slot.Utils.clamp(Number(c.backdropOpacity)||0,0,.9)})`;layer.style.setProperty('--luck-glow',c.glowColor||'#ffd33d');title.textContent=c.titleText||'';title.style.fontSize=`${Number(c.titleFontSizePx)||46}px`;title.style.color=c.titleColor||'#fff186';layer.classList.add('show');const count=Math.max(1,Math.round(Number(c.symbolCount)||34)),size=Math.max(10,Number(c.symbolSizePx)||70),spread=Math.max(100,Number(c.horizontalSpreadPx)||780),fall=Math.max(100,Number(c.fallDurationMs)||1200),stagger=Math.max(0,Number(c.staggerMs)||75);for(let i=0;i<count;i++){const img=document.createElement('img');img.className='luck-falling-dollar';img.src=imageUrlFor('dollar');img.alt='';img.style.width=img.style.height=`${size}px`;img.style.left=`${50+(Math.random()-.5)*Math.min(100,spread/8)}%`;host.appendChild(img);const drift=(Math.random()-.5)*140,delay=i*stagger;img.animate([{transform:`translate3d(0,-${size}px,0) rotate(0deg)`,opacity:0},{offset:.08,opacity:1},{offset:.82,opacity:1},{transform:`translate3d(${drift}px,${Slot.Config.reels.cellHeight*3+size*2}px,0) rotate(${360+(Math.random()*360)}deg)`,opacity:0}],{duration:fall,delay,easing:'linear',fill:'both'}).finished.catch(()=>{}).finally(()=>img.remove());}return Slot.Utils.delay(Math.max(100,Number(c.showerDurationMs)||3300)).then(()=>{layer.classList.remove('show');host.innerHTML='';});};
  R.applyFreeSpinFeatureStyle=function(){const f=Slot.Config.freeSpinsFeature||{},layer=document.getElementById('free-spins-feature-layer'),card=document.getElementById('free-spins-feature-card'),img=document.getElementById('free-spins-feature-symbol');if(!layer||!card)return;layer.style.background=`rgba(0,0,0,${Slot.Utils.clamp(Number(f.backdropOpacity)||0,0,1)})`;card.style.width=`${Number(f.widthPx)||460}px`;card.style.minHeight=`${Number(f.minHeightPx)||360}px`;card.style.padding=`${Number(f.paddingYPx)||0}px ${Number(f.paddingXPx)||0}px`;card.style.borderWidth=`${Number(f.borderWidthPx)||0}px`;card.style.borderRadius=`${Number(f.borderRadiusPx)||0}px`;card.style.fontFamily=f.fontFamily||'Arial, sans-serif';card.style.fontWeight=String(Number(f.fontWeight)||1000);card.style.transform=`scale(${Number(f.popupScale)||1})`;card.style.background=`linear-gradient(180deg,${f.backgroundColor||'#0068b8'},${f.backgroundColor2||'#003e74'})`;card.style.borderColor=f.borderColor||'#d9e5ee';card.style.setProperty('--feature-accent',f.accentColor||'#ffe884');img.style.transform=`scale(${Number(f.symbolScale)||1})`;const title=document.getElementById('free-spins-feature-title'),subtitle=document.getElementById('free-spins-feature-subtitle');if(layer.dataset.variant==='pigBurst'){const p=Slot.Config.pigBurstPopup||{};title.textContent=p.titleText||'';subtitle.textContent=p.subtitleText||'';title.style.fontSize=`${Number(p.titleFontSizePx)||38}px`;subtitle.style.fontSize=`${Number(p.subtitleFontSizePx)||22}px`;title.style.color=p.titleColor||'#fff6b4';subtitle.style.color=p.subtitleColor||'#eef8ff';title.style.fontFamily=subtitle.style.fontFamily=p.fontFamily||f.fontFamily||'Arial, sans-serif';title.style.fontWeight=subtitle.style.fontWeight=String(Number(p.fontWeight)||1000);title.style.letterSpacing=`${Number(p.letterSpacingPx)||0}px`;title.style.lineHeight=String(Number(p.lineHeight)||1.08);}else{title.style.fontSize=`${Number(f.titleFontSizePx)||42}px`;subtitle.style.fontSize=`${Number(f.subtitleFontSizePx)||22}px`;title.style.color='';subtitle.style.color='';title.style.fontFamily=subtitle.style.fontFamily='';title.style.fontWeight=subtitle.style.fontWeight='';title.style.letterSpacing='';title.style.lineHeight='';}};

  R.applyCashoutMenuStyle=function(){const c=Slot.Config.cashoutMenu||{},items=document.querySelectorAll('.account-readout span'),values=document.querySelectorAll('.account-readout b'),shadow=c.textShadowEnabled?'0 1px 1px rgba(255,255,255,.65)':'none';items.forEach(el=>{el.style.fontFamily=c.fontFamily||'Arial, sans-serif';el.style.fontSize=`${Number(c.labelFontSizePx)||20}px`;el.style.fontWeight=String(Number(c.fontWeight)||900);el.style.setProperty('color',c.labelColor||'#000','important');el.style.letterSpacing=`${Number(c.letterSpacingPx)||0}px`;el.style.lineHeight=String(Number(c.lineHeight)||1.15);el.style.setProperty('text-shadow',shadow,'important');el.style.webkitTextStroke='0 transparent';el.style.padding=`${Number(c.paddingPx)||0}px`;el.style.borderWidth=`${Number(c.borderWidthPx)||0}px`;el.style.borderRadius=`${Number(c.borderRadiusPx)||0}px`;});values.forEach(el=>{el.style.fontSize=`${Number(c.valueFontSizePx)||30}px`;el.style.setProperty('color',c.valueColor||'#000','important');el.style.setProperty('text-shadow',shadow,'important');el.style.webkitTextStroke='0 transparent';});};
  document.addEventListener('slot:settings-changed',event=>{if(event.detail?.path?.startsWith('cashoutMenu.'))R.applyCashoutMenuStyle();});

  R.buildPaytable=function(){const host=document.getElementById('paytable-list');if(!host||!Slot.GameMath?.placeholderPays)return;host.innerHTML='';const bet=Math.max(0,Number(Slot.State.bet)||0),credits=mult=>Math.round(bet*Number(mult||0)).toLocaleString();['wild','bank','money','hammer','A','K','Q','J'].forEach(id=>{const cfg=Slot.Config.symbols[id],p=Slot.GameMath.placeholderPays[id];const row=document.createElement('div');row.className='pay-row';const img=document.createElement('img');img.src=imageUrlFor(id);img.alt=cfg.name;const name=document.createElement('span');name.className='pay-name';name.textContent=cfg.name;const pay=document.createElement('strong');pay.innerHTML=`3 = ${credits(p.three)} CREDITS<br>4 = ${credits(p.four)} CREDITS`;row.append(img,name,pay);host.appendChild(row);});};

  R.applyAllSettings=function(){document.documentElement.style.setProperty('--reel-blue',Slot.Config.reels.backgroundColor);const expected=Slot.Config.reels.count,geometryChanged=R.reels.length!==expected||R.reels.some(r=>r.cells.length!==Number(Slot.Config.reels.symbolBufferCells));if(geometryChanged)R.createReels();else{R.reels.forEach(r=>{r.element.style.width=`${Slot.Config.reels.reelWidth}px`;r.element.style.height=`${Slot.Config.reels.rows*Slot.Config.reels.cellHeight}px`;r.element.style.backgroundColor=Slot.Config.reels.backgroundColor;r.element.style.borderRightColor=Slot.Config.reels.dividerColor;r.cells.forEach(c=>{c.dom.style.width=`${Slot.Config.reels.reelWidth}px`;c.dom.style.height=`${Slot.Config.reels.cellHeight}px`;});});const host=document.getElementById('reels');host.style.width=`${Slot.Config.reels.count*Slot.Config.reels.reelWidth}px`;host.style.height=`${Slot.Config.reels.rows*Slot.Config.reels.cellHeight}px`;host.style.backgroundColor=Slot.Config.reels.backgroundColor;R.refreshSymbolStyles();R.renderReelPositions();}R.applyLayout();R.applyPopupStyle();R.applyFreeSpinFeatureStyle();R.buildPaytable();R.applyPaytableStyle();R.applyFreeSpinsCounterStyle();};
})();
